### ISSUE TITLE
Não funciona....

### ISSUE THREAD

**Issue by ApenasGamer** [marcos10pc/cmsp-cheeto#1]
Talvez eu seja estúpido ou algo assim, mas não pega, segui perfeitamente o mini tutorial...

**Comment by marcos10pc** [comment]
Skill issue

**Comment by marcos10pc** [comment]
Meme, tenta ativar modo desktop no celular

**Comment by ApenasGamer** [comment]
Opa, vim dizer que eu era burro mesmo, aparentemente é preciso do modo de desenvolvedor ativo nas extensões para funcionamento correto, peço muitas desculpas por isso.
