### ISSUE TITLE
Nota de satisfação!!!

### ISSUE THREAD

**Issue by Vzdiguu** [marcos10pc/cmsp-cheeto#2]
Cara, simplesmente um genioooo, eu valorizo isso!! Parabens pelo desenvolvimento do script, esta funcionando muito bem! minha nota é 10, não deixe de atualizar caso preciso, se necessario estou disposto a ajudar. SHOOOOOOOWWWWWW

**Comment by marcos10pc** [comment]
Deus abencoe
